# Generated by Django 4.0.4 on 2022-06-29 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=' ', upload_to='user/passport')),
                ('Name', models.CharField(max_length=100)),
                ('phone', models.IntegerField(default='0')),
                ('email', models.EmailField(max_length=50)),
                ('Address', models.CharField(max_length=100)),
                ('skill', models.CharField(max_length=100)),
                ('Degree', models.CharField(max_length=100)),
                ('DegreePassingYear', models.DateField()),
                ('DegreeBranch', models.CharField(max_length=100)),
                ('Degreeinstitude', models.CharField(max_length=100)),
                ('Degreepercent', models.IntegerField(default='0')),
                ('HSC', models.CharField(max_length=100)),
                ('HSCPassingYear', models.DateField()),
                ('HSCBranch', models.CharField(max_length=100)),
                ('HSCinstitude', models.CharField(max_length=100)),
                ('HSCpercent', models.IntegerField(default='0')),
                ('SCCYear', models.DateField()),
                ('SCCinstitude', models.CharField(max_length=100)),
                ('SCCpercent', models.IntegerField(default='0')),
                ('CertificateName', models.CharField(max_length=100)),
                ('CourceName', models.CharField(max_length=100)),
                ('CourceDate', models.DateField()),
                ('ProjectTitle', models.CharField(max_length=100)),
                ('ProjectName', models.CharField(max_length=100)),
                ('ProjectDate', models.DateField()),
            ],
        ),
    ]
