# Generated by Django 4.0.4 on 2022-07-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_userinfo_careerobjective'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
