# Generated by Django 4.0.4 on 2022-07-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0003_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=' ', upload_to='user/passport')),
                ('Name', models.CharField(default=' ', max_length=100)),
                ('Designation', models.CharField(default=' ', max_length=50)),
                ('phone', models.IntegerField(default='0')),
                ('Altphone', models.IntegerField(default='0')),
                ('email', models.EmailField(default=' ', max_length=50)),
                ('Address', models.CharField(default=' ', max_length=100)),
                ('Dist', models.CharField(default=' ', max_length=100)),
                ('pincode', models.IntegerField(default='0')),
                ('skill', models.CharField(default=' ', max_length=100)),
                ('CareerObjective', models.TextField(default='')),
                ('Degree', models.CharField(default=' ', max_length=100)),
                ('DegreePassingYear', models.DateField()),
                ('DegreeBranch', models.CharField(default=' ', max_length=100)),
                ('Degreeinstitude', models.CharField(max_length=100)),
                ('DegreeCGPA', models.CharField(default=' ', max_length=20)),
                ('Degreepercent', models.IntegerField(default='0')),
                ('HSC', models.CharField(max_length=100)),
                ('HSCPassingYear', models.DateField()),
                ('HSCBranch', models.CharField(max_length=100)),
                ('HSCinstitude', models.CharField(max_length=100)),
                ('HSCpercent', models.IntegerField(default='0')),
                ('HSCCGPA', models.CharField(default=' ', max_length=20)),
                ('SCCYear', models.DateField()),
                ('SCCinstitude', models.CharField(max_length=100)),
                ('SCCpercent', models.IntegerField(default='0')),
                ('CertificateName', models.CharField(max_length=100)),
                ('CourceName', models.CharField(max_length=100)),
                ('CourceDate', models.DateField()),
                ('ProjectTitle', models.CharField(max_length=100)),
                ('ProjectName', models.CharField(max_length=100)),
                ('ProjectDate', models.DateField()),
                ('CompanyName', models.CharField(default=' ', max_length=50)),
                ('JobDesignation', models.CharField(default=' ', max_length=50)),
                ('JobDescription', models.TextField(default=' ')),
                ('JobStart', models.DateField()),
                ('Present', models.CharField(max_length=20)),
                ('JobSend', models.DateField(default=' ')),
            ],
        ),
    ]
