# Generated by Django 4.0.4 on 2022-07-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='ProjectStatus',
            field=models.CharField(default=' ', max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='skillFive',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='skillFour',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='skillSecond',
            field=models.CharField(default=' ', max_length=100),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='skillThird',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
